### ISSUE TITLE
Mesur.io needs to update issuer to latest VC-API options

### ISSUE THREAD

**Issue by aljones15** [w3c-ccg/vc-test-suite-implementations#55]
https://github.com/w3c-ccg/vc-api-test-suite-implementations/blob/b95d0a73c635031584c14b16373d5e7a1feae5f2/implementations/Mesur.io.json#L14-L16

Mesur.io still needs an `options` object with `type: Ed25519Signature2018 ` passed to their issuer.
`options.type` is no longer in the VC-API https://w3c-ccg.github.io/vc-api/#issue-credential except in the context of `credentialStatus`.

**Comment by BigBlueHat** [comment]
Related to #81. Not sure what the status is/should be. @brownoxford would love to catch-up with what y'all need/want here.

Thanks!
🎩

**Comment by JSAssassin** [comment]
Closing, since `mesur.io` is no longer in the implementations' list.
