### ISSUE TITLE
Consider renaming the repo to `vc-test-suite-implementations`

### ISSUE THREAD

**Issue by JSAssassin** [w3c-ccg/vc-test-suite-implementations#82]

**Comment by BigBlueHat** [comment]
This repo looks to be used across the CCG for configuring all CCG level test suites--making it analogous to https://github.com/w3c/vc-test-suite-implementations for the WG.

Could we rename this to make that clear @msporny @man4prez @kwlinson?

GitHub should handle the repo, issue, and PR related redirects.

**Comment by JSAssassin** [comment]
@BigBlueHat I am okay with that.

**Comment by BigBlueHat** [comment]
@w3c-ccg/chairs could one of you rename this repository to `vc-test-suite-implementations`? or grant me the super powers to do so? I'm leading the work on test suites here and in the VCWG.

Thanks!
🎩

**Comment by JSAssassin** [comment]
Closing. Addressed by #92
