### ISSUE TITLE
Rename README Tag sections to Opting into a Test Suite

### ISSUE THREAD

**Issue by aljones15** [w3c-ccg/vc-test-suite-implementations#89]
The README does not contain instructions on which endpoints are needed for opting into a test suite.

So this section needs to be revised:

https://github.com/w3c-ccg/vc-api-test-suite-implementations/blob/44120afe67957a71cd1fe510cf142267c5a5ce01/README.md?plain=1#L129-L150

1. Either replace the Tag Section with a new Section `## Opting into a Test Suite`
2. in the new section provide instructions on which endpoints are needed for to opt into a test suite, where in the manifest to add them, and which tag the endpoint will need

Example:
```md
## Opting into a Test Suite
### Ed25519Signature2020
You will need to add a VC API complaint issuer and verifer that support the Ed25519Signature2020 to your implementation.
Example:
```js
{
  "issuers": [{
      "id": "urn:uuid:my:implementation:issuer:id",
      "endpoint": "https://product.example.com/issuers/foo/credentials/issue",
    "tags": ["Ed25519Signature2020"]
  }],
  "verifiers": [{
    "id": "https://product.example.com/verifiers/z19uokPn3b1Z4XDbQSHo7VhFR",
    "endpoint": "https://product.example.com/verifiers/z19uokPn3b1Z4XDbQSHo7VhFR/credentials/verify",
    "tags": ["Ed25519Signature2020"]
  }]
}
```

**Comment by JSAssassin** [comment]
Closing. Addressed by #91
